# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pr:
  branches:
    include:
    - master
    - releases/*
  paths:
    include:
    - e2e_samples/parking_sensors/src/ddo_transform/*

variables:
  WORKING_DIR: 'e2e_samples/parking_sensors/src/ddo_transform'

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

- script: pip install -r requirements_dev.txt && pip install -r requirements.txt
  workingDirectory: $(WORKING_DIR)
  displayName: 'Install requirements'

- script: make lint && make tests 
  workingDirectory: $(WORKING_DIR)
  displayName: 'Run lint tests'